os:
- linux
sudo: required

language: go
go:
    - 1.8.4
    - 1.9.1
env:
    - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
    #- git config --global url."git@github.com:".insteadOf "https://github.com/"
    - go get -u github.com/golang/dep/cmd/dep
install:
    - dep ensure -v
script:
    - go test -race -cpu 1,4 -cover -run=. -bench=. ./counter ./env ./nanshal ./probe ./tagcleaner ./tracing ./zerocopy
